app/__init__.py
import os
from flask import Flask
from app.views.task import mod as task_module

app = Flask(__name__)
app.config.from_object('config')

app.register_blueprint(task_module)

port = int(os.environ.get("PORT", 5000))

app/views/task.py
from flask import Blueprint, render_template, redirect, url_for, request, jsonify
# from werkzeug import secure_filename
from app.db import db, tasks
import json

mod = Blueprint('task', __name__)


@mod.route('/', methods=['GET'])
def index():
    return render_template('task/index.html')


@mod.route('/create', methods=['GET'])
def new():
    task = ""
    return render_template('task/create.html', task=task, action=url_for('task.create'))


@mod.route('/create', methods=['POST'])
def create():
    form_data = request.form.to_dict()
    tasks.insert(form_data)
    return redirect('/')


@mod.route('/show/<int:task_id>')
def show(task_id):
    task = tasks.find_one(id=task_id)
    return render_template('task/show.html', task=task)


@mod.route('/edit/<int:task_id>', methods=['GET'])
def edit(task_id):
    task = tasks.find_one(id=task_id)
    return render_template('task/edit.html', task=task, action=url_for('task.update', task_id=task_id))


@mod.route('/edit/<int:task_id>', methods=['POST'])
def update(task_id):
    form_data = request.form.to_dict()
    form_data['id']=task_id
    tasks.update(form_data, ['id'])
    return redirect('/')


@mod.route('/delete/<int:task_id>', methods=['POST'])
def delete(task_id):
    tasks.delete(id=task_id)
    return redirect('/')


@mod.route('/contact/', methods=['GET'])
def contact():
    return render_template('task/contact.html')


@mod.route('/showall/', methods=['GET'])
def showall():
    tasks = db.query('SELECT id, name, description, active FROM tasks')
    return render_template('task/showall.html', tasks=tasks)


#JSON
@mod.route('/get/<int:task_id>')
def get(task_id):
    pass


@mod.route('/all')
def all():
    tasks = db.query('SELECT id, name, description, active FROM tasks')
    all_tasks = []
    for task in tasks:
        if task['active'] == '0':
            active = 'Inativa'
        else:
            active = 'Ativa'
        all_tasks += [(task['id'], task['name'], task['description'], active)]

    return jsonify(tasks=all_tasks)
    #return jsonify(task_list = [task for tasks in tasks.all()])

app/templates/task/_form.html
<script language="javascript" type="text/javascript">
    function formValidate() {

        var taskName = Task.taskName.value;
        var taskDescription = Task.taskDescription.value;
     
        if (taskName == "") {
            alert('Preencha o campo com o nome da tarefa!');
            Task.taskName.focus();
            return false;
        }

        else if (taskDescription == "") {
            alert('Preencha o campo com a descrição da tarefa!');
            Task.taskDescription.focus();
            return false;
        }

        else {
            alert('Tarefa enviada com sucesso!');
        }
    }
</script>

<form action="{{ action }}" method="post" name="Task" onsubmit="return formValidate()">
    <p>
        <label>Task Name:<br/>
            <input type="text" class="form-control" name="name" id="taskName" placeholder="{{ task['name'] }}">
        </label>
    </p>
    <p>
        <label>Description:<br/>
            <textarea type="text" class="form-control" name="description" id="taskDescription" placeholder="{{ task['description'] }}"></textarea>
        </label>
    </p>
    <p>
        <label>Status:<br/>
            <select name="active">
                <option value="0">Inativa</option>
                <option selected value="1">Ativa</option>
            </select>
        </label>
    </p>
    <input type="submit" class="btn btn-primary" value="Enviar">
    <a class="btn btn-danger" href="/">Cancelar</a>
</form>

app/templates/task/contact.html
{% extends "task/layout.html" %}
{% block content %}

<div class="jumbotron">
    <h1>Contact</h1>
    <p>
        Get in touch: frederico.duarte.vieira@gmail.com
        <a class="btn btn-primary pull-right" href="/">Voltar</a>
    </p>
</div>

{% endblock %}

app/templates/task/create.html
{% extends "task/layout.html" %}
{% block content %}
<h1>Insert Task</h1>

{% include "task/_form.html" %}

{% endblock %}

app/templates/task/edit.html
{% extends "task/layout.html" %}
{% block content %}

<h1>Edit Task - Id: {{ task['id'] }}</h1>

{% include "task/_form.html" %}

{% endblock %}

app/templates/task/index.html
{% extends "task/layout.html" %}
{% block content %}

    <div class="jumbotron">
        <h1>To Do List</h1>
        <p>To do list to manage daily tasks</p>
    </div>

    <a class="btn btn-primary" href="{{ url_for('task.create') }}">Create</a>
    <button class="btn btn-warning" id="edit">Edit Task</button>
    <button class="btn btn-danger" id="delete">Delete Task</button>
    <button class="btn btn-info" id="show">Show Task</button>

    <h2>Show Tasks by Datatable and JSON</h2>

    <table id="todo-table" class="table" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Description</th>
                <th>Status</th>
            </tr>
        </thead>
    </table>
{% endblock %}

app/templates/task/layout.html
<!DOCTYPE html>
<html>
    <head>

        <script type="text/javascript" src="/static/js/jquery-1.12.0.js"></script>
        <script type="text/javascript" src="/static/js/jquery.dataTables.js"> </script>
        <script type="text/javascript" src="/static/js/table.js"></script>

        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://cdn.datatables.net/1.10.10/css/jquery.dataTables.min.css"/>
        <link rel="stylesheet" href="/static/css/bootstrap.min.css">
        <link rel="stylesheet" href="/static/css/style.css">
        <title>To Do List</title>
    </head>
    <body>
      <header>
        <nav class="navbar navbar-inverse navbar-fixed-top">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="
              false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="{{ url_for('task.index') }}">#ToDoList</a>
            </div>
            <div id="navbar" class="collapse navbar-collapse">
              <ul class="nav navbar-nav">
                <li class="active"><a href="{{ url_for('task.index') }}">Home</a></li>
                <li><a href="{{ url_for('task.showall') }}">Show All</a></li>
                <li><a href="{{ url_for('task.contact') }}">Contact</a></li>
              </ul>
            </div>
          </div>
        </nav>
      </header>
        <div class="container">
          {% block content %}
          {% endblock %}
        </div>
    </body>
    <footer>
      <div class="container">
        <p>
          Copyright 2016 Frederico Duarte Vieira  
        </p>
      </div>
    </footer>
</html>

app/templates/task/show.html
{% extends "task/layout.html" %}
{% block content %}

<h1>Show Task - Id: {{ task['id']}}</h1>

<b>Name:</b> {{ task['name'] }} </br>
<b>Description:</b> {{ task['description'] }} </br>
<b>Status:</b> {{ 'Inativa' if task['active'] == '0' else 'Ativa' }}</br>

<a class="btn btn-primary pull-right" href="/">Voltar</a>

{% endblock %}

app/templates/task/showall.html
{% extends "task/layout.html" %}
{% block content %}

<h1>Show All Tasks</h1>

{% for task in tasks %}
    <p>
        <b>Id:</b> {{ task['id'] }} </br>
        <b>Name:</b> {{ task['name'] }} </br>
        <b>Description:</b> {{ task['description'] }} </br>
        <b>Status:</b> {{ 'Inativa' if task['active'] == '0' else 'Ativa' }}</br>
    </p>
{% endfor %}

<a class="btn btn-primary pull-right" href="/">Voltar</a>

{% endblock %}